version: '3.8'

services:
  vue_app:
    build:
      context: ./vue # Caminho para o diretório Vue
      dockerfile: Dockerfile # Se o Dockerfile estiver no diretório correto
    container_name: vue_app
    ports:
      - "80:80"  # Exponha o Nginx na porta 8080
    networks:
      - app_network  # Especifica a rede para o Vue

  django:
    build:
      context: .
    container_name: django_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles  # Verifique se você tem esse volume
    depends_on:
      - mysql  # Garante que o Django inicie após o MySQL
    networks:
      - app_network  # Especifica a rede para o Django

  mysql:
    image: mysql:8.0  # Agora usando a versão 8.0 do MySQL
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Defina a senha do usuário root
      MYSQL_DATABASE: defaultdb  # Nome do banco de dados para o Django
      MYSQL_USER: avnadmin  # Nome do usuário
      MYSQL_PASSWORD: AVNS_s_YJIYpw7l_iSnL3raN  # Senha do usuário
    ports:
      - "3306:3306"  # Expõe a porta do MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Persistência dos dados do MySQL
    networks:
      - app_network  # Especifica a rede para o MySQL

networks:
  app_network:
    driver: bridge

volumes:
  staticfiles:  # Declaração do volume nomeado "staticfiles"
  mysql_data: