# Generated by Django 3.2.12 on 2024-01-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquadramento_tributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('nome_contato', models.CharField(max_length=300)),
                ('tempo_atividade', models.IntegerField()),
                ('quant_socios', models.IntegerField()),
                ('quant_funcionarios', models.IntegerField()),
                ('ramo_atividade', models.CharField(max_length=300)),
                ('principal_atividade', models.CharField(max_length=300)),
                ('receita_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_investimento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enquadramento_tributario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analise.enquadramento_tributario')),
            ],
        ),
    ]
