# Generated by Django 3.2.12 on 2024-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_lancamento_DRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='historico_empresa',
            field=models.TextField(default='kkk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='pontos_criticos',
            field=models.TextField(default='111'),
            preserve_default=False,
        ),
    ]
