# Generated by Django 3.2.12 on 2024-04-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0004_dre_mensal_lancamento_dre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DRE_mensal',
            new_name='DREmensal',
        ),
    ]
