# Generated by Django 3.2.12 on 2024-04-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0005_rename_dre_mensal_dremensal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DREmensal',
            new_name='DRE_mensal',
        ),
    ]
