# Generated by Django 3.2.12 on 2024-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0006_rename_dremensal_dre_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_lancamento_dre',
            name='natureza',
            field=models.CharField(choices=[('receita', 'Receita'), ('custos_variaveis', 'Custos Variáveis'), ('custos_fixos', 'Custos Fixos')], default='receita', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='receita_anual',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='total_investimento',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
