# Generated by Django 3.2.12 on 2024-04-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0007_auto_20240414_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento_dre',
            name='DRE_mensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_DRE', to='analise.dre_mensal'),
        ),
    ]
